### ISSUE TITLE
Authors Can not Generate Shortlink

### ISSUE THREAD

**Issue by TheLibertyWolf** [norcross/yourls-link-creator#9]
It seems that when an author publishes an article, the shortlink is not generated. And the module does not appear in post-new.php and post.php. But it works very well for an administrator and a Editor.

**Comment by norcross** [comment]
that is by design. however, that is filterable using the `yourls_user_cap` filter. you can even target which action (ajax, display, etc) is being done. so just pass a capability that includes authors.

**Comment by TheLibertyWolf** [comment]
Thank you for the quick reply. How can I put this into action? I tried with a plugin that adds capabilities to the roles but it does not work. Is it possible to create the option in the plugin settings?

**Comment by norcross** [comment]
You'd want to use a function like this in your theme, functionality plugin, or an MU plugin.
```php
add_filter( 'yourls_user_cap', 'myexampleprefix_add_authors_to_yourls', 10, 2 );
/**
 * Modify the default user capability to allow for authors.
 * Use the available list on https://codex.wordpress.org/Roles_and_Capabilities#Capability_vs._Role_Table
 *
 * @param  string $capability  The current capability. The default is 'edit_others_posts'.
 * @param  string $action      The current action being taken. Usually can stay as-is.
 *
 * @return string
 */
function myexampleprefix_add_authors_to_yourls( $capability, $action ) {

	// Return a capability that matches
	// the user role you want to allow.
	return 'publish_posts';
}
```

**Comment by TheLibertyWolf** [comment]
Thank you very much for your help. And thank you for taking the time to explain to me.

**Comment by norcross** [comment]
you’re welcome!
